# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project '../emojiWords.xcodeproj'

target 'emojiWords' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for emojiWords
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'Google-Mobile-Ads-SDK'

end
